### ISSUE TITLE
configure script reports that ncursesw isn't installed, when it is

### ISSUE THREAD

**Issue by ghost** [yuewangny/twilc#1]
I have installed `ncurses` through MacPorts and yet whenever I run `./configure`, I get this error:

> configure: error: ncursesw not found

**Comment by SteamedFish** [comment]
MacPorts installs libraries into a non-standard location. You should tell `./configure` where the library is. 
You should use `./configure ----includedir=<MacPorts directory>/include/`
For example, `./configure --includedir=/opt/local/include/` if your MacPorts is located at `/opt/local/`

**Comment by ghost** [comment]
@SteamedFish I tried that, and I get the same error.

**Comment by SteamedFish** [comment]
Have you installed  `ncursesw` library other than `ncurses`? `ncursesw` is also required.  We should add this to the dependencies list.

**Comment by ghost** [comment]
I have installed both `ncursesw` and `ncurses`.

**Comment by SteamedFish** [comment]
Can you post the full information `./configure` prints?
The script works under my Mac.

**Comment by ghost** [comment]
Sure:

> checking for a BSD-compatible install... /opt/local/bin/ginstall -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for style of include used by make... GNU
> checking dependency style of gcc... gcc3
> checking for cos in -lm... yes
> checking for initscr in -lncursesw... no
> configure: error: ncursesw not found

The output is the same if I use the `--includedir` solution you proposed.

**Comment by SteamedFish** [comment]
Wired. Can you find  `/opt/local/include/cursesw.h` on your system?  Can you try `./configure --prefix=/opt/local/` ?
I don't know what's happening. I'll try find a clean installed Mac to test tomorrow. 
It's 01:30 am in China. Have to sleep. Sorry. :-)

**Comment by ghost** [comment]
Yes, `/opt/local/include/cursesw.h` exists. And the solution you posted still doesn't work.

**Comment by SteamedFish** [comment]
http://dreness.com/wikimedia/index.php?title=How_to_compile_other_software_using_Macports_libraries
This is a guide of how to compile programs using Macports libraries. 
I found a clean installed Mac, got the same issue as you, and after I tried this guide it worked.

**Comment by ghost** [comment]
That worked! Thank you!
